name: Beta Release

on:
  push:
    branches:
      - 'release/beta*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build Release
        run: cargo build --release --bins
        
      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp target/release/nimble dist/
          cp target/release/nimble-gui dist/
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: beta-artifacts
          path: dist/*
          
      - name: Create Beta Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "beta-${GITHUB_SHA::8}" \
            --title "Beta Release ${GITHUB_SHA::8}" \
            --prerelease \
            --notes "Automated beta release from ${GITHUB_REF#refs/heads/}" \
            dist/*
