name: Beta Release

on:
  push:
    branches:
      - 'release/beta*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get version from Cargo.toml
        id: get_version
        shell: bash
        run: |
          version=$(grep '^version = ' Cargo.toml | cut -d '"' -f 2)
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache cargo registry
        uses: actions/cache@v3 
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Release
        shell: bash
        run: |
          set -eo pipefail
          cargo build --release --bins

      - name: Package Windows Release
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist
          Copy-Item "target\release\nimble-cli.exe" -Destination "dist\"
          Copy-Item "target\release\nimble-gui.exe" -Destination "dist\"
          Compress-Archive -Path "dist\*" -DestinationPath "nimble-windows.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nimble-windows
          path: nimble-windows.zip
          
      # - name: Create Beta Release
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh release create "beta-${env:GITHUB_SHA.Substring(0,8)}" `
      #       --title "Beta Release ${{ steps.get_version.outputs.version }}" `
      #       --prerelease `
      #       --notes "Beta release from branch ${env:GITHUB_REF#refs/heads/}" `
      #       nimble-windows.zip
